import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { rateLimit } from "@/lib/rate-limit";
import { generatePDFBuffer, type PDFData, type BusinessInfo } from "@/lib/pdf-generator";
import { createClient } from "@/lib/supabase/server";

const getResendClient = () => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey || apiKey === "placeholder") return null;
  return new Resend(apiKey);
};

/** Strip dangerous HTML: <script>, <iframe>, on* event handlers */
function sanitizeHtml(html: string): string {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, "")
    .replace(/\bon\w+\s*=\s*"[^"]*"/gi, "")
    .replace(/\bon\w+\s*=\s*'[^']*'/gi, "");
}

export async function POST(request: NextRequest) {
  try {
    // Check if user is authenticated
    const supabase = await createClient();
    const user = supabase ? (await supabase.auth.getUser()).data.user : null;
    const isAuthenticated = !!user;

    // Rate limit: authenticated = 5/hr, unauthenticated = 2/hr
    const rateLimitResponse = rateLimit(request, {
      windowMs: 60 * 60 * 1000,
      maxRequests: isAuthenticated ? 5 : 2,
      prefix: "email",
    });
    if (rateLimitResponse) return rateLimitResponse;

    const body = await request.json();
    const { to, subject, document_number, client_name, html_content, pdf_data, business_info, is_reminder } = body;

    let finalSubject = subject;
    let finalHtml = html_content;

    if (is_reminder) {
       finalSubject = `[Reminder] Action Required: ${subject}`;
       finalHtml = `<div style="background-color: #fffbeb; padding: 16px; border-left: 4px solid #f59e0b; margin-bottom: 24px; color: #92400e; font-family: sans-serif;">
            <p style="margin: 0; font-weight: 600;">Reminder Notice</p>
            <p style="margin: 4px 0 0 0; font-size: 14px;">This is an automated reminder regarding ${document_number} via BillCraft.</p>
       </div>` + finalHtml;
    }

    if (!to || !subject || !html_content) {
      return NextResponse.json(
        { error: "Missing required fields: to, subject, html_content" },
        { status: 400 }
      );
    }

    // Validate email — single recipient only
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(to) || to.includes(",")) {
      return NextResponse.json(
        { error: "Invalid or multiple email addresses. Send to one recipient." },
        { status: 400 }
      );
    }

    // Cap HTML content length
    if (html_content.length > 50000) {
      return NextResponse.json(
        { error: "Email content too large (max 50KB)" },
        { status: 400 }
      );
    }

    const sanitizedContent = sanitizeHtml(finalHtml);

    const resend = getResendClient();

    if (!resend) {
      return NextResponse.json(
        {
          error: "Email service not configured. Add RESEND_API_KEY to .env.local",
          demo: true,
        },
        { status: 503 }
      );
    }

    // Generate PDF attachment if data is provided
    let attachments: { filename: string; content: Buffer }[] | undefined;
    if (pdf_data) {
      try {
        const pdfBuffer = await generatePDFBuffer(
          pdf_data as PDFData,
          (business_info || {}) as BusinessInfo
        );
        const filename = `${document_number || "document"}.pdf`;
        attachments = [{ filename, content: pdfBuffer }];
      } catch (pdfErr) {
        console.error("PDF generation error:", pdfErr);
        // Continue without attachment — don't block the email
      }
    }

    const { data, error } = await resend.emails.send({
      from: "BillCraft <noreply@billcraft.in>",
      to: [to],
      subject: finalSubject || `${document_number} from BillCraft`,
      html: `
        <div style="font-family:'Segoe UI',system-ui,sans-serif;max-width:600px;margin:0 auto;">
          <div style="background:#0a0a0a;padding:24px;border-radius:12px 12px 0 0;">
            <h1 style="color:#f59e0b;font-size:20px;margin:0;">BillCraft</h1>
          </div>
          <div style="padding:24px;background:#ffffff;border:1px solid #eee;">
            <p style="color:#333;font-size:14px;line-height:1.6;">
              Hi${client_name ? ` ${client_name}` : ""},
            </p>
            <p style="color:#333;font-size:14px;line-height:1.6;">
              Please find the ${document_number ? `document (${document_number})` : "document"} details below.${attachments ? " A PDF copy is attached." : ""}
            </p>
            <div style="margin:24px 0;padding:20px;background:#fafafa;border-radius:8px;border:1px solid #eee;">
              ${sanitizedContent}
            </div>
            <p style="color:#888;font-size:12px;margin-top:24px;">
              Generated by <a href="https://billcraft.vercel.app" style="color:#f59e0b;">BillCraft</a> — AI Invoice & Proposal Generator
            </p>
          </div>
        </div>
      `,
      ...(attachments ? { attachments } : {}),
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { error: "Failed to send email. Please try again." },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      messageId: data?.id,
      hasAttachment: !!attachments,
    });
  } catch (error) {
    console.error("Email error:", error);
    return NextResponse.json(
      { error: "Failed to send email." },
      { status: 500 }
    );
  }
}
