import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service — Invosmith",
  description: "Invosmith terms of service — usage terms and conditions.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-dark-900">
      <Navbar />
      <div className="pt-32 pb-20 section-padding">
        <div className="mx-auto max-w-3xl prose-invert">
          <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8">Last updated: March 2026</p>

          <div className="space-y-8 text-sm text-gray-300 leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Service Overview</h2>
              <p>Invosmith is an AI-powered invoice and proposal generator. The service generates professional documents from your project descriptions. By using Invosmith, you agree to these terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Beta Service</h2>
              <p>Invosmith is currently in free beta. All features are available at no cost during the beta period. The free tier allows 3 documents per month. No credit card is required. Features and limits may change as we develop paid plans.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. Data Storage</h2>
              <p>All your data is stored locally in your browser. Invosmith does not store your business data on any server. You are responsible for backing up your data using the export feature in Settings.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. AI-Generated Content</h2>
              <p>Documents generated by Invosmith are AI-assisted. While we strive for accuracy, you are responsible for reviewing all generated content — including amounts, tax calculations, and client details — before sending to clients. Invosmith is not a licensed accounting or tax service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. GST Compliance</h2>
              <p>Invosmith calculates GST based on the information you provide (GSTIN, state codes). The accuracy of GST calculations depends on correct input. Consult a qualified CA for complex GST scenarios.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-400">
                <li>Use the service to generate fraudulent invoices.</li>
                <li>Attempt to bypass usage limits or rate limits.</li>
                <li>Reverse-engineer the AI prompts or generation pipeline.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
              <p>Invosmith is provided &ldquo;as is&rdquo; as a free beta service. We are not liable for any errors in generated documents, tax miscalculations, or losses arising from use of the service. GST calculations are provided as a convenience and should be verified independently.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. Contact</h2>
              <p>Questions about these terms? Email <span className="text-amber-400">hello@invosmith.in</span></p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
}
